---
#
# Ansible automation file
#   1. Install mysql server on the db host(s)
#   2. Create application database
#   3. Create application user and password
#   4. Upload table creation + seed data script
#   5. execute script mentioned in setp 4
#
# Run with `ansible-playbook mysql.yml`
#
# 'devops' is name of a group of hosts in /etc/ansible/hosts
- hosts: devops
  vars_files: 
#   separate code and data
	- db_vars.yml                         
  become: yes
  tasks:
   - name: Ensure that MySQL is up and running and enabled at boot
     service: name=mysql state=started enabled=true
   - name: create an application database
     mysql_db:
       name: '{{ database.name }}'
       state: present
       login_user: root
       login_password: '{{ root_password }}'
   - name: create application user
     mysql_user:
       name: '{{ database.username }}'
       password: '{{ database.password }}'
       host: '%'
       priv: '{{ database.name }}.*:ALL'
       login_user: root
       login_password: '{{ root_password }}'
       state: present
   - name: Upload table creation script
     copy:
       src: ./homehearth.sql
       dest: /tmp/
   - name: Create application table and some data records
     mysql_db:
       state: import
       name: '{{ database.name }}'
       target: /tmp/homehearth.sql
       login_user: root
       login_password: '{{ root_password }}'
