---
# tasks file for apache2
- name: Install PHP7 with the most common packages
  apt-get:
    name: "{{ item }}"
    state: present
  with_items:
    - php7.0
    - php7.0-gd
    - php7.0-imap
    - php7.0-mbstring
    - php7.0-mysqlnd
    - php7.0-opcache
    - php7.0-pdo
    - php7.0-pdo-mysql
    - php7.0-phar
    - php7.0-readline
  notify: restart Apache
- name: Upload index.php file to EC2 instance
  copy:
    src: index.php
    dest: /var/www/html
    owner: www-data
    group: www-data